-- Q1. What is the total revenue generated by male vs. female customers?
select gender , avg(purchase_amount) as amount from tables
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount from tables
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from tables);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating),2) as rate from tables
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type , round(avg(purchase_amount),2) from tables
where shipping_type in ('Express','Standard')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status , count(customer_id) as total_customers , round(avg(purchase_amount),2) as avg_spend ,round(sum(purchase_amount),2) as total_revenue from tables
group by subscription_status
order by total_revenue , avg_spend desc ;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(100 * sum(case when discount_applied = 'Yes'Then 1 else 0 end)/count(*) * 100,2) as discount_rate from tables
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

 

-- Q8. What are the top 3 most purchased products within each category? 
-- with item_counts as (
--     select category,item_purchased, count(customer_id) as total_orders,
-- 		ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank from customer
--     group by  category, item_purchased
-- )
-- select item_rank,category, item_purchased, total_orders from tables
-- where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
       count(customer_id) as repeat_buyers
from tables
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) AS total_revenue from tables
GROUP BY age_group
ORDER BY total_revenue desc;
